### ISSUE TITLE
Usage instructions / debugging for docker container?

### ISSUE THREAD

**Issue by charlesincharge** [WildMeOrg/wildbook-ia#192]
Hi, I wanted to try out `wildbook-ia` through the docker container but was having some trouble launching it. The logs show a few different errors, but I'm not sure which are relevant. Is there a user guide?

For reference, I am running on Ubuntu 20.04, Docker version 20.10.6, with a GPU.

Thanks!
Charles

```
(computer-vision) ~/Development/computer-vision$ sudo docker container run --rm -p 5000 --gpus all --name wildbook-ia -v /media/data/ComputerVisionCourse/:/data/docker/ wildme/wbia:latest
+ setup
+ exec gosu root:root /virtualenv/env3/bin/python -m wbia.dev --dbdir /data/db --logdir /data/db/logs --web --containerized --production
/wbia/wildbook-ia/wbia/plottool/__MPL_INIT__.py:176: MatplotlibDeprecationWarning: 
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  mpl.rcParams[key] = ''
Local docker client is not available
DEVMAIN INIT - POSTLOGGING
 + --- dev.py Intro ---
 | ___ _  _ ____    ___  ____ _  _  ___  _   _    ____ ____ ____ _ ___  ___ 
 |  |  |__| |___    |  \ |___ |  |  |__]  \_/     [__  |    |__/ | |__]  |  
 |  |  |  | |___    |__/ |___  \/  .|      |      ___] |___ |  \ | |     |  
 |                                                                          
 | 
 L ___ dev.py Intro ___

++dev
[update_schema_version] checkpath('//data/db/_ibsdb/_ibeis_database_backup_v0.0.0.sqlite3')
[update_schema_version] ... does not exist
[util_path] [Copying]: 
[C] | //data/db/_ibsdb/_ibeis_database.sqlite3
[C] ->//data/db/_ibsdb/_ibeis_database_backup_v0.0.0.sqlite3
*** failed to load general config
Traceback (most recent call last):
  File "/wbia/wildbook-ia/wbia/control/manual_meta_funcs.py", line 1010, in _init_config
    general_config = ut.load_cPkl(config_fpath, verbose=ut.VERBOSE)
  File "/wbia/wbia-utool/utool/util_io.py", line 357, in load_cPkl
    with open(fpath, 'rb') as file_:
FileNotFoundError: [Errno 2] No such file or directory: '/data/db/general_config.cPkl'
DEVMAIN INIT - PRELOGGING
[ensuredir] checkpath('/data/db/logs')
[ensuredir] ... does not exist
[util_path] mkdir('/data/db/logs')
logging to log_fpath='/data/db/logs/wbia_logs_0000.out'
[pref] Saving to /data/db/cfg.cPkl

[util_list] +--- DEBUG DUPLICATE ITEMS  'visual_uuid_list' ---
[util_list] |There are 0 duplicates
[util_list] L--- FINISH DEBUG DUPLICATE ITEMS ---

[update_schema_version] checkpath('//data/db/_ibsdb/_ibeis_staging_backup_v0.0.0.sqlite3')
[update_schema_version] ... does not exist
[util_path] [Copying]: 
[C] | //data/db/_ibsdb/_ibeis_staging.sqlite3
[C] ->//data/db/_ibsdb/_ibeis_staging_backup_v0.0.0.sqlite3
[util_path] [Copying]: 
[C] | //data/db/_ibsdb/_ibeis_database.sqlite3
[C] ->/data/db/_ibsdb/_ibeis_backups/_ibeis_database_backup_2021_04_28_21_43_43.sqlite3
[util_path] [Copying]: 
[C] | //data/db/_ibsdb/_ibeis_staging.sqlite3
[C] ->/data/db/_ibsdb/_ibeis_backups/_ibeis_staging_backup_2021_04_28_21_43_43.sqlite3
JobBackend ports:
varname-not-found = {
    'collect_pull_url': 'tcp://127.0.0.1:1329',
    'collect_push_url': 'tcp://127.0.0.1:3265',
    'engine_fast_push_url': 'tcp://127.0.0.1:22299',
    'engine_pull_url': 'tcp://127.0.0.1:16872',
    'engine_slow_push_url': 'tcp://127.0.0.1:32923',
}
Initialize Background Processes
Deleting 0 leftover engine locks
JobInterface ports:
port_dict = {
    'collect_pull_url': 'tcp://127.0.0.1:1329',
    'collect_push_url': 'tcp://127.0.0.1:3265',
    'engine_fast_push_url': 'tcp://127.0.0.1:22299',
    'engine_pull_url': 'tcp://127.0.0.1:16872',
    'engine_slow_push_url': 'tcp://127.0.0.1:32923',
}
Initializing JobInterface
connect engine_pull_url = 'tcp://127.0.0.1:16872'
connect collect_pull_url = 'tcp://127.0.0.1:1329'
Reloading 0 engine jobs...
Processed 0 records
0it [00:00, ?it/s]
Registered 0 jobs...
	 0 completed jobs
	 0 restarted jobs
	 0 suppressed jobs
	 0 corrupted jobs
Archived 0 jobs...
Updating completed job counter: {'__set_jobcounter__': 0}
Re-sending 0 engine jobs...
0it [00:00, ?it/s]Using TensorFlow backend.
WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1517: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Using TensorFlow backend.
WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1517: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Using TensorFlow backend.
WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1517: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

Using TensorFlow backend.
WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1517: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1519: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1519: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1519: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From /wbia/wildbook-ia/wbia/web/job_engine.py:1519: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2021-04-28 21:43:45.066671: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-28 21:43:45.066666: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-28 21:43:45.066669: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-28 21:43:45.066666: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-04-28 21:43:45.072351: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-04-28 21:43:45.072437: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-04-28 21:43:45.072789: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8ef3440 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.072808: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-28 21:43:45.072838: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8ef4150 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.072853: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-28 21:43:45.074333: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-04-28 21:43:45.074801: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8ef4420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.074821: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-28 21:43:45.074866: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-28 21:43:45.074870: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-28 21:43:45.077324: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-28 21:43:45.089719: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2199995000 Hz
2021-04-28 21:43:45.090253: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8ef4420 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.090274: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-04-28 21:43:45.092377: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2021-04-28 21:43:45.358817: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.359476: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.359480: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.359492: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.359675: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8f93190 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.359693: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1060 with Max-Q Design, Compute Capability 6.1
2021-04-28 21:43:45.359874: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.360516: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8f82670 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.360529: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1060 with Max-Q Design, Compute Capability 6.1
2021-04-28 21:43:45.360535: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8f93190 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.360551: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1060 with Max-Q Design, Compute Capability 6.1
2021-04-28 21:43:45.360680: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x8f92ee0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2021-04-28 21:43:45.360690: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: NVIDIA GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:01:00.0
2021-04-28 21:43:45.360695: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1060 with Max-Q Design, Compute Capability 6.1
2021-04-28 21:43:45.360698: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.360726: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.360871: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.361275: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: NVIDIA GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:01:00.0
2021-04-28 21:43:45.361438: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: NVIDIA GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:01:00.0
2021-04-28 21:43:45.361499: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Found device 0 with properties: 
name: NVIDIA GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.48
pciBusID: 0000:01:00.0
2021-04-28 21:43:45.362044: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.362045: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.362047: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.362083: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.362089: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-28 21:43:45.362101: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-28 21:43:45.362108: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-28 21:43:45.362150: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2021-04-28 21:43:45.377176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-04-28 21:43:45.377176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-04-28 21:43:45.377176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-04-28 21:43:45.377176: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2021-04-28 21:43:45.377290: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-04-28 21:43:45.377292: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-04-28 21:43:45.377303: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-04-28 21:43:45.377301: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2021-04-28 21:43:45.413274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-04-28 21:43:45.413274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-04-28 21:43:45.413276: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-04-28 21:43:45.413274: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2021-04-28 21:43:45.435025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-04-28 21:43:45.435026: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-04-28 21:43:45.435025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-04-28 21:43:45.435029: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2021-04-28 21:43:45.501610: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-28 21:43:45.501613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-28 21:43:45.501613: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-28 21:43:45.501622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2021-04-28 21:43:45.502090: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.502098: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.502102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.502102: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.506661: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.506881: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.506885: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.506961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.508279: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-04-28 21:43:45.509118: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.510563: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-04-28 21:43:45.510599: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-04-28 21:43:45.510626: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0
2021-04-28 21:43:45.510771: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.510818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.510820: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2021-04-28 21:43:45.513657: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-28 21:43:45.513712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2021-04-28 21:43:45.513735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2021-04-28 21:43:45.515602: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.516063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-28 21:43:45.516111: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2021-04-28 21:43:45.516128: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2021-04-28 21:43:45.516284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-28 21:43:45.516330: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2021-04-28 21:43:45.516348: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2021-04-28 21:43:45.516838: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.517026: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1180] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-04-28 21:43:45.517080: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1186]      0 
2021-04-28 21:43:45.517106: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1199] 0:   N 
2021-04-28 21:43:45.517110: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.517720: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.518619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.520309: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.520344: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.521332: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-04-28 21:43:45.522079: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5164 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-04-28 21:43:45.523333: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5164 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-04-28 21:43:45.523805: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5164 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-04-28 21:43:45.524662: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1325] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 5164 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
```

**Comment by bluemellophone** [comment]
While it doesn't look like it, that Docker image did launch successfully.  It was most likely listening on `localhost:5000` and awaiting web requests.  The errors you see at the bottom of the log are related to GPU-enabled compute and the container not being able to find a suitable CUDA device.
